# Generated by Django 3.2.1 on 2021-05-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
